export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST'
export const TRAINER_LIST_SUCCESS = 'TRAINER_LIST_SUCCESS'
export const TRAINER_LIST_FAIL = 'TRAINER_LIST_FAIL'

export const TRAINER_DETAILS_REQUEST = 'TRAINER_DETAILS_REQUEST'
export const TRAINER_DETAILS_SUCCESS = 'TRAINER_DETAILS_SUCCESS'
export const TRAINER_DETAILS_FAIL = 'TRAINER_DETAILS_FAIL'

export const TRAINER_DELETE_REQUEST = 'TRAINER_DELETE_REQUEST'
export const TRAINER_DELETE_SUCCESS = 'TRAINER_DELETE_SUCCESS'
export const TRAINER_DELETE_FAIL = 'TRAINER_DELETE_FAIL'

export const TRAINER_CREATE_REQUEST = 'TRAINER_DELETE_REQUEST'
export const TRAINER_CREATE_SUCCESS = 'TRAINER_DELETE_SUCCESS'
export const TRAINER_CREATE_FAIL = 'TRAINER_DELETE_FAIL'
export const TRAINER_CREATE_RESET = 'TRAINER_DELETE_RESET'

export const TRAINER_UPDATE_REQUEST = 'TRAINER_UPDATE_REQUEST'
export const TRAINER_UPDATE_SUCCESS = 'TRAINER_UPDATE_SUCCESS'
export const TRAINER_UPDATE_FAIL = 'TRAINER_UPDATE_FAIL'
export const TRAINER_UPDATE_RESET = 'TRAINER_UPDATE_RESET'












