# Generated by Django 4.1.7 on 2023-05-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
