# Generated by Django 4.1.7 on 2023-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_sections_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='students',
        ),
        migrations.AlterField(
            model_name='sections',
            name='trainers',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainers', to='base.trainers'),
        ),
    ]
