# Generated by Django 4.1.7 on 2023-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_trainers_sections_remove_trainers_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='trainers',
        ),
        migrations.AddField(
            model_name='sections',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainers', to='base.students'),
        ),
    ]
